Events
newhorizon-tech/math-magicians pull request #3
Opened 2021-10-22 14:44 UTC by newhorizon-tech

- Add calculator logic
- Add event handling
- Use Props and State

2021-10-22 23:14 UTC, eliasecasta requested changes
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @newhorizon-tech, I am Elias, your reviewer for this PR

Well done so far with your project!

The design is accurate and almost all the requirements are met, keep it up!

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [x] The calculator click events are not working
- [x] Please check the comments below this PR for extra details.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561) you have a limited number of code reviews per project (you can check the exact number in your Dashboard). If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-22 23:14 UTC, eliasecasta commented on src/components/Calculator.js
> +            <Row key={row} rowButtons={row} handleCalc={() => this.handleCalc} />
- [x] - [ ] I am unable to use the calculator, the on-click events seem to not be working as expected, please take a second look at that and fix it because it is a requirement for this milestone to have a fully working calculator.

2021-10-23 00:02 UTC, wandji20 requested changes
Hello, @newhorizon-tech  :raised_hands: 
-----
Great :muscle:  job :raised_hands:  implementing the requested changes.
However, there are a few issues you need to address to have this project approved.

## Status: Require Changes :recycle: :red_circle: 
Please check the comments below and under the review and make all required changes.
Optional comments are not required to mark this project approved
- [x] There is a bug with your calculator division functionality. Kindly fix that
![Screenshot from 2021-10-23 00-57-43](https://user-images.githubusercontent.com/65476715/138534449-6911c3b6-758b-42ae-b671-0392db84d777.png)

**Happy coding :computer:** 
**_Do not hesitate to make comments in this PR in case of doubts._**
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-23 00:11 UTC, wandji20 approved these changes
## Hi @newhorizon-tech  :raised_hands:

##### You have done exceptionally well, and have met all requirements for this project :+1:

# Status: Approved 👍 :partying_face: 

Your project has been approved, however, Keep up the good work.

## Congratulations :+1:  :fireworks: 

_Go ahead and merge this branch. Also, don't forget to submit the project completion form.
Good luck with your next project :mechanical_arm:  :slightly_smiling_face:_ 

 If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-23 01:52 UTC, merged